.SUFFIXES : .ml .mli .cmo .cmi .cmx

MODULES=enum+ bitSet+ dynArray+ extHashtbl+ extList+ extString+ global+ option+ refList+ std+ uChar+ uTF8+

INTERFACES=$(MODULES:+=.cmi)
BYTECODE=$(MODULES:+=.cmo) extLib.cmo
NATIVECODE=$(MODULES:+=.cmx) extLib.cmx
NATIVEOBJS=$(MODULES:+=.obj) extLib.obj $(MODULES:+=.o) extLib.o

all: extLib.cma extLib.cmxa partial_clean

byte: extLib.cma partial_clean

opt: extLib.cmxa partial_clean

extLib.cma: $(INTERFACES) $(BYTECODE)
	ocamlc -a -o $@ $(BYTECODE)

extLib.cmxa: $(INTERFACES) $(NATIVECODE)
	ocamlopt -a -o $@ $(NATIVECODE)

partial_clean:
	rm -f $(BYTECODE) $(NATIVECODE) $(NATIVEOBJS)

clean: partial_clean
	rm -f $(INTERFACES) extLib.cma extLib.cmxa extLib.a extLib.lib extLib.cmi

.ml.cmo:
	ocamlc $(CFLAGS) -c $<

.ml.cmx:
	ocamlopt $(CFLAGS) -c $<

.mli.cmi:
	ocamlc $(CFLAGS) $<

