name: Build

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-version:
          - "4.02"
          - "4.05"
          - "4.11"
          - "4.14"
          - "5"
        os:
          - ubuntu-latest
        include:
          - ocaml-version: "4.14"
            os: macos-latest
          - ocaml-version: "4.14"
            os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-version }}

      - run: opam pin add extlib.dev . --no-action

      - run: opam install . --deps-only --with-doc --with-test

      - run: opam exec -- make minimal=1 test
        if: matrix.os != 'windows-latest'

      - run: opam exec -- make clean
        if: matrix.os != 'windows-latest'

      - run: opam exec -- make test
        if: matrix.os != 'windows-latest'

      - run: opam exec -- ocaml check_stdlib.ml
        if: matrix.os != 'windows-latest'
        continue-on-error: true

      - run: opam exec -- make clean
        if: matrix.os != 'windows-latest'

      - run: opam exec -- dune build @all @runtest
